### ISSUE TITLE
Server Crashes With Mod Installed (1.12.2-1.3.0)

### ISSUE THREAD

**Issue by SockWulf** [DoubleDoorDevelopment/MineSafety#1]
I'm experiencing a crash on my server with MineSafety-1.12.2-1.3.0 installed. Here is the log ..

`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2018-06-27 17:15:58 CEST
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineSafety (minesafety)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at net.doubledoordev.minesafety.MineSafety.<init>(MineSafety.java:40)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:193)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:577)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 38 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@2d84cb86 from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 40 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
    ... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.9.0-6-amd64
  Java Version: 1.8.0_91, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1772576800 bytes (1690 MB) / 2043478016 bytes (1948 MB) up to 2075918336 bytes (1979 MB)
  JVM Flags: 5 total; -Xmx2048M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts -XX:MaxGCPauseMillis=30
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.1.2555 75 mods loaded, 75 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version           | Source                                                   | Signature                                |
       |:----- |:-------------------- |:----------------- |:-------------------------------------------------------- |:---------------------------------------- |
       | UC    | minecraft            | 1.12.2            | minecraft.jar                                            | None                                     |
       | UC    | mcp                  | 9.42              | minecraft.jar                                            | None                                     |
       | UC    | FML                  | 8.0.99.99         | custom.jar                                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UC    | forge                | 14.23.1.2555      | custom.jar                                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UC    | bowinfinityfix       | rv5               | minecraft.jar                                            | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
       | UC    | movillages           | 1.5.4             | [1.12]MoVillages-1.5.4.jar                               | None                                     |
       | UC    | forgeendertech       | 1.12.2-4.3.14.0   | AdChimneys-ForgeEndertech-1.12.2-4.3.14.0-build.0140.jar | None                                     |
       | UC    | applecore            | 3.1.0             | AppleCore-mc1.12.2-3.1.0.jar                             | None                                     |
       | UC    | jei                  | 4.8.5.144         | jei_1.12.2-4.8.5.144.jar                                 | None                                     |
       | UC    | appleskin            | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                               | None                                     |
       | UC    | architecturecraft    | @VERSION@         | architecturecraft-1.12-2.68.jar                          | None                                     |
       | UC    | autocrafter          | 4.2               | autocrafter-4.2.jar                                      | None                                     |
       | UC    | betterthanmending    | 1.1.1             | BetterThanMending-1.1.1.jar                              | None                                     |
       | UC    | bibliocraft          | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                        | None                                     |
       | UC    | biomesoplenty        | 7.0.1.2351        | BiomesOPlenty-1.12.2-7.0.1.2351-universal.jar            | None                                     |
       | UC    | bottledmilk          | 1.0.0             | BottledMilk-1.12-1.1.0.jar                               | None                                     |
       | UC    | carryon              | 1.8               | CarryOn+MC1.12.2+v1.8.jar                                | None                                     |
       | UC    | chisel               | MC1.12.2-0.2.0.31 | Chisel-MC1.12.2-0.2.0.31.jar                             | None                                     |
       | UC    | chiselsandbits       | 14.17             | chiselsandbits-14.17.jar                                 | None                                     |
       | UC    | comforts             | 1.1.2             | comforts-1.12.2-1.1.2.jar                                | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UC    | craftingcraft        | 6.1.3             | CraftingCraft_1.12-6.1.3.jar                             | None                                     |
       | UC    | crafttweaker         | 4.1.4             | CraftTweaker2-1.12-4.1.4.jar                             | None                                     |
       | UC    | crafttweakerjei      | 2.0.0             | CraftTweaker2-1.12-4.1.4.jar                             | None                                     |
       | UC    | cttinycoal           | 1.12.2-1.0.2      | cttinycoal-1.12.2-1.0.2.jar                              | None                                     |
       | UC    | dbag                 | 1.12.2-4.0        | dbag-4.0.jar                                             | None                                     |
       | UC    | dirt2path            | 1.7.0             | dirt2path-1.7.0.jar                                      | None                                     |
       | UC    | display              | 1.2.4             | Display-1.2.4.jar                                        | None                                     |
       | UC    | elevatorid           | 1.3.6             | ElevatorMod-1.12.2-1.3.6.jar                             | None                                     |
       | UC    | csb_ench_table       | 1.1.3             | EnchantingTable-1.12-1.1.3.jar                           | None                                     |
       | UC    | shadowmc             | 3.8.0             | ExtraRails-ShadowMC-1.12-3.8.0.jar                       | None                                     |
       | UC    | extrarails           | 1.3.0             | ExtraRails-1.12-1.3.0.jar                                | None                                     |
       | UC    | fastleafdecay        | v14               | FastLeafDecay-v14.jar                                    | None                                     |
       | UC    | fenceoverhaul        | 1.3.4             | FenceOverhaul-1.3.4.jar                                  | None                                     |
       | UC    | cfm                  | 4.2.0             | furniture-4.2.0-1.12.2.jar                               | None                                     |
       | UC    | hopperducts          | 1.5               | hopperducts-mc1.12-1.5.jar                               | None                                     |
       | UC    | ironchest            | 1.12.2-7.0.44.829 | ironchest-1.12.2-7.0.44.829.jar                          | None                                     |
       | UC    | jepb                 | 1.2.1             | jepb-1.12-1.2.1.jar                                      | None                                     |
       | UC    | jlgm_chatbox         | 1.3.0             | jlgm_chatbox-1.12.2-1.3.0.jar                            | None                                     |
       | UC    | jukebox              | 1.2               | jukebox-1.2.jar                                          | None                                     |
       | UC    | malisiscore          | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                             | None                                     |
       | UC    | malisisdoors         | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                            | None                                     |
       | UE    | minesafety           | 1.3.0             | MineSafety-1.12.2-1.3.0.jar                              | None                                     |
       | UC    | missing_pieces       | 4.3.0             | missing_pieces-1.12.2-4.3.0.jar                          | None                                     |
       | UC    | morebeautifulbuttons | 1.12.2-1.7.3.20   | morebeautifulbuttons-1.12.2-1.7.3.20.jar                 | None                                     |
       | UC    | morebeautifulplates  | 1.12.2-1.0.3      | morebeautifulplates-1.12.2-1.0.3.jar                     | None                                     |
       | UC    | cxlibrary            | 1.6.1             | MoreFurnaces-cxlibrary-1.12.1-1.6.1.jar                  | None                                     |
       | UC    | morefurnaces         | 1.10.5            | MoreFurnaces-1.12.2-1.10.5.jar                           | None                                     |
       | UC    | multiplelights       | 1.0.2             | MultipleLights-1.12.x-1.0.2.jar                          | None                                     |
       | UC    | overlord             | 2.4.10            | Overlord-1.12.2-2.4.10.jar                               | None                                     |
       | UC    | placeableitems       | 3.3               | placeableitems-3.3.jar                                   | None                                     |
       | UC    | quark                | r1.4-125          | Quark-r1.4-125.jar                                       | None                                     |
       | UC    | autoreglib           | 1.3-18            | Quark-AutoRegLib-1.3-18.jar                              | None                                     |
       | UC    | reap                 | 1.5.1             | reap-1.5.1.jar                                           | None                                     |
       | UC    | redstonepaste        | 1.7.5             | redstonepaste-mc1.12-1.7.5.jar                           | None                                     |
       | UC    | sophisticatedwolves  | 3.13.3            | SophisticatedWolves-1.12.2-3.13.3.jar                    | None                                     |
       | UC    | sparkshammers        | 1.7.1             | sparkshammers-1.12.2-1.7.1.jar                           | None                                     |
       | UC    | spiceoflife          | 1.3.11            | SpiceOfLife-mc1.12-1.3.11.jar                            | None                                     |
       | UC    | stacksize            | 1.1               | stacksize-1.12-1.1.jar                                   | None                                     |
       | UC    | chameleon            | 1.12-4.1.3        | StorageDrawers-Chameleon-1.12-4.1.3.jar                  | None                                     |
       | UC    | storagedrawers       | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.7.jar                          | None                                     |
       | UC    | storagedrawersextra  | @VERSION@         | StorageDrawersExtras-1.12-3.1.0.jar                      | None                                     |
       | UC    | farseek              | 2.3               | Streams-Farseek-1.12-2.3.jar                             | None                                     |
       | UC    | streams              | 0.4.4             | Streams-1.12-0.4.4.jar                                   | None                                     |
       | UC    | subcommonlib         | 1.2.0.1           | telepads-subcommonlib-sublib-1.12.2-1.2.0.4.jar          | None                                     |
       | UC    | telepads             | $version          | telepads-1.12.2-1.1.0.5.jar                              | None                                     |
       | UC    | terracart            | 1.12.2-1.2.3      | terracartreloaded-1.12.2-1.2.3.jar                       | None                                     |
       | UC    | totemdefender        | 1.2.8             | TotemDefender-1.12.2-1.2.9.jar                           | None                                     |
       | UC    | uppers               | 0.0.4             | Uppers-0.0.4.jar                                         | None                                     |
       | UC    | vanillafix           | 1.0.9-97          | VanillaFix-1.0.9-97.jar                                  | None                                     |
       | UC    | villagenames         | 2.0               | VillageNames-1.12.2-2.0.jar                              | None                                     |
       | UC    | villagerinventory    | 1.0.5             | VillagerInventory-1.12-1.0.5.jar                         | None                                     |
       | UC    | vtt                  | 0.6.4             | VillagerTrades-1.12-0.6.4.jar                            | None                                     |
       | UC    | waterstrainer        | 3.2.0             | WaterStrainer-1.12-3.2.0.jar                             | None                                     |
       | UC    | wearablebackpacks    | 3.1.2             | WearableBackpacks-1.12.2-3.1.2.jar                       | None                                     |
       | UC    | adchimneys           | 1.12.2-3.3.3.0    | AdChimneys-1.12.2-3.3.3.0-build.0140.jar                 | None                                     |
  Loaded coremods (and transformers): AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CXLibraryCore (MoreFurnaces-cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      FarseekCoreMod (Streams-Farseek-1.12-2.3.jar)
                                        farseek.core.FarseekClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      CTMCorePlugin (Chisel-CTM-MC1.12-0.3.0.15.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
                                        com.github.parker8283.bif.Transformer
                                      CorePlugin (AdChimneys-ForgeEndertech-1.12.2-4.3.14.0-build.0140.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.2.jar)
                                        c4.comforts.asm.SleepTransformer
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
                                        com.chocohead.biab.BornInABarn
                                      LoadingPlugin (Quark-r1.4-125.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      LoadingPlugin (AdChimneys-1.12.2-3.3.3.0-build.0140.jar)
                                        com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
  Suspected Mods: MineSafety (minesafety)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)`

**Comment by Claycorp** [comment]
Fixed in 1.3.1 by 946a00f2e9312af8204c3d519a5a50488f8efe86
