### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Tyrius1** [DoubleDoorDevelopment/MineSafety#5]
love the mod! got a crash report here. https://pastebin.com/J7dNfnBk Running on version 1.14.4 forge version 28.0.95

**Comment by Claycorp** [comment]
I don't think this is my issue.
 ` at com.lycanitesmobs.ClientManager.registerItemColors(ClientManager.java:119) ~[?:1.0] {}`
Points to lycanites mobs. I don't even do anything with item colors IIRC.
