### ISSUE TITLE
Fails on 1.16.3 dedicated server with a client side call.

### ISSUE THREAD

**Issue by mactso** [DoubleDoorDevelopment/MineSafety#6]
FYI... to repeat, simply install only minesafety on a dedicated server and start.   Crash report will include all the details.

You are probably just missing a "world.isremote()" or "if (world instanceof serverworld) somewhere.

Cheers!  I'll be looking forward to the fixed version for our modpack.

**Comment by Claycorp** [comment]
Fixed it, file is on CF.
